### ISSUE TITLE
[Arch] Placing window or door with H1=0 fails

### ISSUE THREAD

**Issue by psommerfeld** [yorikvanhavre/BIM_Workbench#116]
There seems to be no indication that H1 needs a non-zero value.
If H1 is 0 when placing door/window, Report View reports failure shown below.
A warning dialog should appear to indicate when H1 is invalid before placement, or H1 should not accept zero value.

```
08:51:40  Traceback (most recent call last):
  File "/Applications/FreeCAD main 0.20.2.app/Contents/Resources/Mod/Arch/ArchWindow.py", line 889, in execute
    shapes = self.buildShapes(obj)
  File "/Applications/FreeCAD main 0.20.2.app/Contents/Resources/Mod/Arch/ArchWindow.py", line 687, in buildShapes
    wires.append(obj.Base.Shape.Wires[j])
<class 'IndexError'>: list index out of range
08:51:40  Recompute failed! Please check report view.
08:51:40  Traceback (most recent call last):
  File "/Applications/FreeCAD main 0.20.2.app/Contents/Resources/Mod/Arch/ArchWindow.py", line 889, in execute
    shapes = self.buildShapes(obj)
  File "/Applications/FreeCAD main 0.20.2.app/Contents/Resources/Mod/Arch/ArchWindow.py", line 687, in buildShapes
    wires.append(obj.Base.Shape.Wires[j])
<class 'IndexError'>: list index out of range
08:51:40  Recompute failed! Please check report view.
```

About FC:
```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * fasteners.backup1686222008.1392 0.3.50 (Disabled)
  * ProDarkThemePreferencePack 1.0.0
  * BIM 2021.12.0
```

**Comment by yorikvanhavre** [comment]
Indeed I can confirm this. This is an Arch issue however, so I'm moving this issue to the main FreeCAD repo
