### ISSUE TITLE
Workbench Failure

### ISSUE THREAD

**Issue by jdunmire** [yorikvanhavre/BIM_Workbench#60]
BIM was working for me until I updated it today (using the AddOn Manager). Now when I select BIM I get a Workbench failure dialog with the following message:

`No module named 'draftguitools.gui_edit_base_object'`

**The report view shows:**
```
18:08:57  No module named 'draftguitools.gui_edit_base_object'
18:08:57  Traceback (most recent call last):
  File "<string>", line 208, in Initialize
  File "/home/jerry/.FreeCAD/Mod/BIM/archguitools/gui_wall.py", line 37, in <module>
    import archmake.make_wall as make_wall
  File "/home/jerry/.FreeCAD/Mod/BIM/archmake/make_wall.py", line 29, in <module>
    from archobjects.wall import Wall 
  File "/home/jerry/.FreeCAD/Mod/BIM/archobjects/wall.py", line 1001, in <module>
    from draftguitools.gui_edit_base_object import GuiTools
```

**My environment:**
```
OS: Pop!_OS 20.04 LTS (pop:GNOME/pop)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22262 (Git) AppImage
Build type: Release
Branch: master
Hash: f56825c79f11b75648a7a0dcc8a9f52bb4574e61
Python version: 3.8.5
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)
```

**Comment by jdunmire** [comment]
Commit 32d7350 has fixed the problem.
Thank you.
