### ISSUE TITLE
Manage IFC Properties not working

### ISSUE THREAD

**Issue by dimitarsp** [yorikvanhavre/BIM_Workbench#88]
Hi,

I am getting an error when trying to invoke the Manage IFC Properties tool:

```
12:42:00  Running the Python command 'BIM_IfcProperties' failed:
Traceback (most recent call last):
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 126, in Activated
    self.update()
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 177, in update
    self.updateDefault()
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 306, in updateDefault
    if QtCore.QFileInfo(":/icons/Arch_"+obj.Proxy.Type+"_Tree.svg").exists():

'App.DocumentObject' object has no attribute 'Proxy'Running the Python command 'BIM_IfcProperties' failed:
Traceback (most recent call last):
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 126, in Activated
    self.update()
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 177, in update
    self.updateDefault()
  File "C:\Users\dimitar\AppData\Roaming\FreeCAD\Mod\BIM\BimIfcProperties.py", line 306, in updateDefault
    if QtCore.QFileInfo(":/icons/Arch_"+obj.Proxy.Type+"_Tree.svg").exists():

'App.DocumentObject' object has no attribute 'Proxy'
```

Using the latest  BIM WB update and FC windows build:

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.26858 (Git)
Build type: Release
Branch: master
Hash: e209bc706d35121098f9bac779bc6b09c24ddd95
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)

**Comment by yorikvanhavre** [comment]
There is a full redesign planned with #81 so this will become obsolete
